spring:
  application:
    name: runner
  jackson:
    default-property-inclusion: non_null
  main:
    banner-mode: off

logging:
  level:
    com:
      codenrock:
        cloud: ${LOGGER_CODENROCK:DEBUG}
application:
  schedule-rate: ${SCHEDULE_RATE:30}
  base-url: ${BASE_URL:https://mts-olimp-cloud.codenrock.com/api}
  token: ${TOKEN:RAIYbiDFqbdtuVCEvfs0HJtaJGqNrkuv}
  cpu-load-max: ${CPU_LOAD_MAX:95}
  memory-load-max: ${MEMORY_LOAD_MAX:95}
  delta: ${DELTA:10}


